name: SSL Certificate Check

on:
  schedule:
    - cron: '0 8 * * *'   # Runs daily at 08:00 UTC
  workflow_dispatch:       # Allows manual trigger from GitHub UI

jobs:
  ssl_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run SSL check script
        run: |
          python ssl_check.py
